@startuml er
entity Subject {
  + name [PK]
  --
  duration
}

entity Teacher {
  + name [PK]
}

entity Timetable {
  + id [PK]
  --
  section
  day
}

entity TimeSlot {
  + start_time [PK]
  + end_time [PK]
  --
  subject
  teacher
}

Subject ||-o{ TimeSlot
Teacher ||-o{ TimeSlot
Timetable ||-o{ TimeSlot
@enduml