@startuml object
object monday {
  day = "Monday"
}

object mathClass {
  subject = "Math"
  teacher = "Mr. Smith"
  time = "9:00-10:00"
}

object scienceClass {
  subject = "Science"
  teacher = "Ms. Johnson"
  time = "10:00-11:00"
}

monday *-- mathClass
monday *-- scienceClass
@enduml