@startuml package
package "com.example" {
  package "core" {
    [Main]
    [TimetableGenerator]
    [TimetablePrinter]
  }

  package "io" {
    [TimetableFileHandler]
    [UserInputHandler]
  }

  package "test" {
    [MainTest]
    [TimetableGeneratorTest]
  }
}

[Main] --> [TimetableGenerator]
[Main] --> [TimetableFileHandler]
[Main] --> [UserInputHandler]
@enduml