@startuml
left to right direction
actor Administrator as A

usecase (Generate Timetable) as UC1
usecase (Edit Timetable) as UC2
usecase (View Timetable) as UC3
usecase (Save Timetable) as UC4
usecase (Load Timetable) as UC5

A --> UC1
A --> UC2
A --> UC3
A --> UC4
A --> UC5
@enduml